#!/usr/bin/env ruby

require 'getoptlong'

opts = GetoptLong.new(
    ['--issue' , '-i', GetoptLong::OPTIONAL_ARGUMENT]
)

if ARGV.empty?
    puts Dir.glob("*[-]*.yml")
end

opts.each do |opt, arg|
    case opt
    when '--issue'
        puts Dir.glob("#{arg}[-]*.yml")
    end
end
